/* HA.strings — libellés FR/EN/ES + moteur de tokens {clef:champ} / {accord:m:f} */
window.HA = window.HA || {};
HA.strings = (function () {
  "use strict";

  var STR_FR = {
    app_nom: "Healing — se rencontrer",
    tagline: "Le comportement n'est jamais le problème. C'est la solution qu'un enfant a trouvée pour survivre.",
    nav: { guide: "Découvrir", accueil: "Accueil", comportements: "Questionnaire", rapport: "Rapport", hub: "Chemin", engagements: "Engagements", miroir: "Miroir", theorie: "Théorie", compatibilite: "Compatibilité" },
    guide: {
      titre: "Bienvenue. Comment ça marche.",
      sous: "Trois minutes pour comprendre — ensuite, tu décides.",
      ideet: "L'idée en une phrase",
      idee: "Quand tu fais quelque chose qui te fait du mal — boire, scroller, fuir, te rabaisser, plaire — ce n'est pas un défaut. C'est une solution que ton système a trouvée un jour pour survivre. Cette app t'aide à voir qui, en toi, joue encore cette solution… et à lui proposer autre chose.",
      partst: "Ton équipe intérieure — 3 mots à connaître",
      partss: "Dans cette app, on parle de « parts » : des petites voix en toi, chacune avec un rôle.",
      exile: "L'Exilé — le moteur",
      exiled: "La part d'enfance blessée. Elle porte la honte, le vide, la peur d'être quitté. C'est elle qui pousse le comportement.",
      manager: "Le Manager — la stratégie",
      managerd: "La part qui gère avant la crise : le Critique, le Perfectionniste, le Sauveur… Elle organise pour que l'Exilé ne souffre pas.",
      pompier: "Le Pompier — la crise",
      pompierd: "La part d'urgence qui éteint pendant la crise : le Fuyard, l'Ivrogne, le Scroll… Elle agit vite, fort, sans réfléchir.",
      coalition: "Règle d'or : un comportement n'est jamais joué par une seule part. C'est toujours un trio : Exilé × Manager × Pompier.",
      mille: "Et un système, mille symptômes : tous tes comportements se relient à la même signature. On ne traite jamais un symptôme isolé.",
      parcourst: "Le parcours, pas à pas",
      parcourss: "Tout est modifiable, rien n'est noté, rien n'est jugé. « Rien n'est une faute : tout est un indice. »",
      e1t: "Crée un profil", e1d: "Prénom, genre, âge, deux cases à cocher. C'est tout. Tu peux en créer plusieurs — un pour toi, un pour comparer.",
      e2t: "Fais l'inventaire", e2d: "Le questionnaire « Ce qui te ressemble » : 9 familles de comportements, avec recherche. Mode simple : environ 2 minutes. Mode exhaustif : des signes précis pour un rapport plus fin. Coche ce qui te parle, honnêtement.",
      e3t: "3 questions de précision", e3d: "L'affinage : trois questions rapides avant le rapport. Tu peux passer chaque question — on n'invente jamais à ta place.",
      e4t: "Lis ton rapport", e4d: "Cinq sections : ton inventaire, le décodage de chaque comportement, ta signature de système (avec la carte de ta constellation), ton chemin vers le comportement idéal, et ta pierre de touche — une parole pour toi.",
      e5t: "Suis ton chemin", e5d: "Le hub « Ton chemin » : ta pierre de touche personnalisée, la lettre d'engagements, le miroir — qui te déclenche et pourquoi.",
      etapes_note: "Durées réelles : mode simple ≈ 2 min, mode exhaustif ≈ 10–15 min.",
      libret: "Sans profil, tu peux déjà explorer",
      libres: "Trois portes sont ouvertes, même avant de commencer :",
      libre_analyse: "Analyser un comportement", libre_analyse_d: "Décoder n'importe quel comportement, sans questionnaire.",
      libre_theorie: "Lire la théorie", libre_theorie_d: "Le système complet : 13 livres, 55 chapitres, un glossaire.",
      libre_compat: "Comparer deux profils", libre_compat_d: "Deux personnes face à face : ce que chacun déclenche chez l'autre.",
      criset: "Le bouton ♥ « Je ne vais pas bien »",
      crise: "Il est sur toutes les pages. Il n'analyse rien : il éteint. Respiration guidée 4-7-8, numéros d'urgence, et la consigne de ne rien décider d'important aujourd'hui.",
      ethiquet: "Ce que cette app n'est pas",
      ethique: "Ni un avis médical, ni un diagnostic, ni un psy. Chaque lecture est une hypothèse à vérifier avec toi, jamais un verdict. Et tout reste sur ton appareil : aucune donnée ne quitte ton navigateur — pas d'IA, pas de compte, pas de réseau.",
      cta: "Commencer",
      cta_sous: "ou explore librement — la barre du haut est toujours là."
    },
    hub_portrait: "Le portrait", hub_portrait_sous: "Toi au quotidien et en crise — lu depuis ton système",
    portrait: {
      titre: "Ton portrait — au quotidien et en crise",
      sub: "{nom}, lu depuis ton système : {m} managers, {p} pompiers, {e} exilés au cœur.",
      disclaimer: "Un portrait probable, pas un verdict. Chaque ligne est une hypothèse concrète : garde ce qui résonne, corrige ce qui ne te ressemble pas.",
      crise_btn: "Si la crise est là maintenant : ne lis pas ce portrait — va d'abord au bouton ♥.",
      q_titre: "Au quotidien",
      q_sous: "Ce que tes managers — et parfois tes exilés — font de ta vie ordinaire.",
      bascule_titre: "La bascule — quand le quotidien craque",
      bascule_sous: "Chaque manager a son point de rupture : le pompier dans lequel il dérape, et ce qui allume.",
      derive_tpl: "Au quotidien, {manager} : {strategie}. Quand ça craque, il dérape vers {pompier} : {crise}.",
      derive_alt: "L'alternative : {alt}",
      k_titre: "Tes rôles vertueux",
      k_sous: "Le Triangle Dramatique de Karpman lu dans tes parts — et leur conversion vertueuse (chapitre 10-13).",
      k_managers: "Tes managers dominants",
      k_pompiers: "Tes pompiers en crise",
      k_converti: "Conversion :",
      k_pivot: "Question pivot :",
      k_theorie: "Lire « Le Triangle Vertueux : Creator, Challenger, Coach » →",
      c_titre: "En crise",
      c_sous: "Ce que tes pompiers font de ta vie quand le système s'embrase.",
      b_titre: "Le besoin sous tout ça",
      b_sous: "Les exilés au centre : ce qu'ils croient, ce qu'ils cherchent, ce qu'il leur faut.",
      declencheurs_titre: "Tes déclencheurs",
      miroir_titre: "Ton miroir — qui déclenche",
      miroir_ligne: "{nom} — {croyance}",
      miroir_paires: "Ce qui te déclenche chez les autres : {noms}",
      miroir_lien: "Voir le miroir complet →",
      eteint: "Il éteint : {noms}",
      contraire: "Son contraire : {texte}",
      rien: "Rien de saillant détecté pour cette dimension — c'est une information, pas un vide.",
      dim: {
        alimentation: "Alimentation", sport: "Sport", travail: "Travail", rythme: "Rythme",
        social: "Social", famille: "Famille", relations: "Relations", valeurs: "Valeurs", besoins: "Besoins"
      }
    },
    btns: { commencer: "Commencer →", rapport: "Voir mon rapport", imprimer: "Imprimer", exporter_md: "Exporter .md", exporter_json: "Exporter ma session", importer: "Importer", effacer: "Tout effacer", modifier: "Modifier", pause: "Pause — je reprends plus tard", revenir: "Revenir", continuer: "Continuer →" },
    familles_intro: "Coche ce qui te ressemble, honnêtement. Tu peux tout modifier. Rien n'est une faute : tout est un indice.",
    famille_averti: "Cette partie parle de désir, de blocages et de stratégies sexuelles. Tu peux la sauter et y revenir.",
    famille_averti_auto: "Cette partie parle de comportements qui font du mal au corps. Les cocher n'est pas un diagnostic — mais si tu te fais du mal, tu as le droit d'être accompagné·e. En France, une ligne d'écoute : 3114 (gratuit, 24 h/24). Tu peux sauter cette famille et y revenir.",
    q_titre: "Ce qui te ressemble",
    frequence_label: "Fréquence",
    frequences: { quotidien: "Quotidien", hebdomadaire: "Hebdomadaire", en_crise: "En crise", rare: "Rare" },
    depuis_label: "Depuis",
    depuiss: { enfance: "L'enfance", adolescence: "L'adolescence", adulte: "L'âge adulte" },
    signes_label: "Ces exemples te parlent ? Coche ceux qui résonnent — ça compte comme « je me reconnais » (lecture large, poids réduit). Pour un poids plein, coche une combinaison précise ci-dessous.",
    recherche_placeholder: "Tape : scroll, argent, colère, fuite…",
    cochés: "cochés",
    rien_coché: "Rien n'est coché pour l'instant — et c'est déjà une réponse.",
    reconnaissances: "reconnaissance(s) large(s)",
    deja_detaillees: "combinaison(s) détaillée(s) déjà cochée(s) — elles comptent toujours",
    mode_simple: "Simple",
    mode_simple_sous: "Les catégories et « je me reconnais » — environ 2 minutes",
    mode_exhaustif: "Exhaustif",
    mode_exhaustif_sous: "Les signes précis et les combinaisons de parts — rapport plus fin",
    note_large: "Lecture large : tu as reconnu des catégories sans préciser les combinaisons. Pour un rapport plus fin, passe au questionnaire exhaustif.",
    note_large_cta: "Passer à l'exhaustif",
    combinaisons_cochees: "combinaison(s) cochée(s)",
    declencheur_prefix: "Déclencheur : ",
    pdt_titre: "LA PIERRE DE TOUCHE",
    pdt_pourquoi: "Pourquoi cette parole ?",
    regles_titre: "Les règles strictes",
    regles_confirm: "J'ai lu ces règles — elles encadrent mes engagements.",
    signature_titre: "Ta signature de système",
    cycle_titre: "Le cycle qui te fait tourner",
    symptomes_titre: "Un système, mille symptômes",
    enfance_titre: "La décision d'enfance (hypothèse)",
    rapport_codes_lien: "Comprendre comment une protection devient une prison — les Codes (chapitre 11-11) →",
    chemin_titre: "Ton chemin, de l'Actual vers l'Ideal",
    rapport_vertueux_lien: "Mes rôles vertueux — le Triangle Dramatique de mes parts (page Portrait) →",
    decode_titre: "Le décodage : comportements → combinaisons de parts",
    inventaire_titre: "Ce que tu as coché",
    scores_titre: "Les scores de tes parts",
    scores_note: "Ce sont des lectures, pas des verdicts. À vérifier avec toi.",
    familles_touchees: "Familles touchées : ",
    rapport_simple: {
      titre: "Rapport simple",
      sous: "L'essentiel de ton rapport — ta signature, ton chemin, ta pierre de touche.",
      btn: "Rapport simple",
      sous_btn: "l'essentiel, sans les diagrammes",
      exiles: "Exilé(s) au cœur",
      managers: "Managers dominants",
      pompiers: "Pompiers de secours",
      declencheurs: "Déclencheurs",
      couts: "Ce que ça coûte",
      inventaire: "{n} combinaison(s) cochée(s) — familles touchées : {f}.",
      chemin_vide: "Aucun comportement clé pour l'instant."
    },
    seq_obligatoire: "Séquence obligatoire :",
    hub_titre: "{nom}, ton rapport est là quand tu veux.",
    hub_intro: "Trois chemins maintenant. Prends le temps.",
    hub_engagements: "Engagements", hub_engagements_sous: "La lettre à soi-même — à imprimer, à relire",
    hub_miroir: "Miroir théorique", hub_miroir_sous: "Qui me déclenche — et pourquoi",
    hub_theorie: "Théorie", hub_theorie_sous: "Comprendre le système complet",
    miroir_titre: "Ton miroir théorique",
    miroir_formule: "Même blessure + stratégie opposée + part désavouée portée",
    miroir_noms: {
      invisible: "L'Existence Gratuite", humilie: "La Dignité Inattaquable", abandonne: "La Présence qui Reste",
      terrifie: "La Sécurité Incarnée", coupable: "L'Innocence Accordée", parentifie: "La Vulnérabilité Assumée"
    },
    miroir_paires: "Les paires qui te concernent",
    miroir_triangle_titre: "Le triangle que vous jouez à deux",
    miroir_triangle_tes: "Tes parts jouent",
    miroir_triangle_ses: "ses parts jouent",
    miroir_triangle_theorie: "Conversion vertueuse : chapitre 10-13 →",
    miroir_stades: "Les 4 stades de l'éveil",
    miroir_garde: "Vrai miroir ou leurre ?",
    miroir_4q: "Les 5 questions du miroir",
    miroir_4q_sub: "Réponds librement — les 4 premières viennent du texte fondateur « Déclencheur d'éveil ». La 5e est la question magique de l'IFS : elle transforme la projection en porte d'entrée vers l'Exilé.",
    miroir_decodage_titre: "Le décodage des projections",
    miroir_decodage_sous: "L'héritage de Carl Jung traduit en IFS : chaque réaction viscérale est une porte vers l'Ombre.",
    miroir_decodage_col_reaction: "Si je réagis ainsi…",
    miroir_decodage_col_type: "C'est une projection de…",
    miroir_decodage_col_ombre: "Ce qui est verrouillé dans l'Ombre (à réintégrer)",
    miroir_decodage_col_cle: "L'indice",
    miroir_pdt_titre: "LA PIERRE DE TOUCHE — miroir",
    compat_porte_sous: "Deux profils face à face, le miroir entre eux",
    compat_sub: "Le miroir appliqué à deux systèmes : ce que chacun déclenche chez l'autre.",
    compat_taux_titre: "Taux d'écho miroir",
    compat_taux_sous: "Deux lois, un seul mécanisme : même blessure (résonance) + stratégie opposée (complémentarité) + part désavouée vécue sans honte.",
    compat_taux_resonance: "Résonance — même blessure",
    compat_taux_complementarite: "Complémentarité — stratégie opposée",
    compat_taux_desavouee: "Part désavouée — vécue sans honte",
    compat_taux_seuil_faible: "Écho faible : les deux systèmes se croisent à peine.",
    compat_taux_seuil_marque: "Écho marqué : vos ombres se répondent — c'est un terrain de travail.",
    compat_taux_seuil_intense: "Écho intense : vos ombres se cherchent. Ce miroir est un levier puissant.",
    compat_peu_profils: "Il faut au moins deux profils pour comparer. Crée un second profil depuis la page d'accueil.",
    compat_pas_de_donnees: "— questionnaire non rempli",
    compat_managers: "Managers dominants",
    compat_pompiers: "Pompiers de secours",
    compat_choisir_a: "Profil A",
    compat_choisir_b: "Profil B",
    compat_blessure_titre: "La blessure",
    compat_blessure_oui: "Exilés communs au cœur — vous portez la même blessure : {noms} ({croyance})",
    compat_blessure_oui_risque: "Vous vous comprenez sans mots. Risque : personne ne voit l'éléphant, le système se renforce.",
    compat_blessure_non: "Blessures différentes : {a} / {b}",
    compat_blessure_non_texte: "Vous ne parlez pas la même langue de la blessure. Le miroir s'active par contraste : ce qui manque à l'un, l'autre le porte.",
    compat_aucune_blessure: "Pas d'exilé détecté (questionnaire vide).",
    compat_aussi: "aussi : ",
    compat_danses_titre: "Danses miroirs croisées",
    compat_mindmap_titre: "Mindmap des deux systèmes",
    compat_danses_sub: "Les paires du miroir où vos deux systèmes se rencontrent.",
    compat_attraction: "{a} fait {profil_a} (via {viaA}) — {b} porte le miroir : {miroir_b} (via {viaB})",
    compat_meme_role: "Même rôle dans la même danse — {a} via {viaA}, {b} via {viaB} : {profil_a}",
    compat_aucune_danse: "Aucune paire du miroir ne croise ces deux systèmes.",
    compat_langages_titre: "Comment l'autre attend des excuses",
    compat_langages_sous: "Selon ses parts dominantes :",
    compat_langages_vide: "Complète le questionnaire de ce profil pour le savoir.",
    compat_attachement_titre: "La danse d'attachement",
    compat_attachement_evitant: "Évitant ↔ Préoccupé",
    compat_attachement_fuyards: "Deux fuyards : chacun se retire, personne ne poursuit. Le manque s'installe en silence.",
    compat_attachement_poursuivants: "Deux poursuivants : intensité sans retrait. L'angoisse monte vite, la demande déborde.",
    compat_attachement_chaos: "Désorganisé en jeu — approche-fuite :",
    compat_attachement_aucun: "Aucun style d'attachement dominant détecté.",
    compat_projections_titre: "Projections croisées",
    compat_projections_sous: "Ce que chacun projette sur l'autre — la règle d'or : ce qui m'irrite ou me fascine chez l'autre est une partie de moi que je ne connais pas encore.",
    compat_proj_vers: "{a} projette sur {b}",
    compat_proj_ombre_managers: "Ombre sombre — le Manager juge chez l'autre ce qu'il a exilé :",
    compat_proj_ombre_pompiers: "Ombre sombre — en crise, le Pompier verra une menace :",
    compat_proj_or: "Ombre dorée — l'or que l'Exilé délègue :",
    theorie_recherche: "Rechercher dans la théorie…",
    theorie_titre: "Théorie — le Système Triaxial",
    theorie_lus: "lus",
    quand_label: "Quand :",
    engagements_titre: "Engagements — la lettre à soi-même",
    engagements_sub: "Chaque engagement transforme un pattern identifié en un geste observable. Tu peux reformuler, retirer, ajouter — c'est TA lettre.",
    rapport_titre_prefix: "REVERSE COMPORTEMENT — ",
    wipe_confirm: "Tout effacer ? Cette action est définitive. Tu peux d'abord exporter ta session.",
    wipe_done: "Tout a été effacé. Cette page n'a rien gardé.",
    partielle: "Lecture partielle — complète ton questionnaire quand tu veux.",
    clique_carte: "Exilé au centre — Managers qui protègent — Pompiers qui éteignent. Clique sur un cercle pour voir sa fiche.",
    clique_cycle: "Clique sur une station du cycle pour la lire.",
    cycle_selecteur: "Voir le cycle depuis :",
    signature_selecteur: "Voir le détail de :",
    carte_selecteur: "Voir la carte de :",
    carte_globale_titre: "Ta constellation de parts",
    carte_globale_legende: "Vue d'ensemble — les 3 exilés dominants au centre, les managers qui protègent et les pompiers qui éteignent autour. Clique sur un cercle pour voir sa fiche.",
    carte_vue_label: "Afficher :",
    carte_vue_globale: "Constellation — vue d'ensemble",
    signature_vue_label: "Voir :",
    signature_vue_recit: "Récit",
    signature_vue_fiche: "Fiche détaillée",
    pdt_selecteur: "Pierre de touche de :",
    chemin_selecteur: "Étape de la séquence :",
    constellation_plein_ecran: "Plein écran",
    constellation_fermer: "Fermer",
    clique_chemin: "Clique sur un jalon pour voir ce qui s'y joue.",
    /* carte personnalisée (3 exilés) + mode crise + pondération mode simple */
    pdt_carte_titre: "Ma pierre de touche",
    pdt_carte_sous: "Une parole personnalisée, bâtie sur tes {n} exilés principaux — {noms}.",
    crise_btn: "Je ne vais pas bien",
    crise_titre: "Je ne vais pas bien",
    crise_sub: "On n'analyse rien : on éteint. Ton système est en alerte — ce n'est pas le moment de comprendre, c'est le moment de sécuriser.",
    crise_consigne: "Ne décide de rien d'important aujourd'hui. Un système en alerte ne prend pas de bonnes décisions.",
    crise_respi_titre: "La respiration 4-7-8",
    crise_respi_etapes: "Inspire par le nez 4 secondes — Retiens 7 secondes — Expire par la bouche 8 secondes",
    crise_respi_conseil: "Répète 4 cycles. Si tu peux, pose une main sur le ventre et une sur le cœur.",
    crise_urgence_titre: "Si c'est une urgence",
    crise_liens_titre: "Quand le corps se calme",
    crise_liens_texte: "Deux protocoles de la théorie, à faire une fois le souffle revenu :",
    miroir_micro_titre: "Le réveil en micro-pas — à cocher quand c'est fait",
    miroir_micro_compat: "Micro-pas du réveil",
    miroir_boucles: "Les boucles d'interaction",
    miroir_boucle_cycle: "Le ping-pong",
    miroir_boucle_sortie: "Comment casser la boucle",
    conflit_titre: "Ce que ce comportement déclenche chez les autres",
    conflit_danse: "La danse prévisible :",
    conflit_lien: "Voir la paire dans le Miroir →",
    arret_label: "Dans l'instant",
    hub_arret_titre: "J'ai envie de…",
    hub_arret_sub: "Choisis un comportement — le protocole d'arrêt immédiat s'affiche.",
    hub_langages_titre: "Mes langages de l'amour principaux",
    hub_langages_sous: "Selon tes parts dominantes — comment les nourrir.",
    hub_langages_vide: "Complète le questionnaire pour découvrir tes langages.",
    hub_proactif_titre: "Ma garde proactive",
    hub_proactif_sous: "Le déclencheur se coupe la veille, pas sur le moment. Coche ce que tu as fait aujourd'hui.",
    hub_proactif_du_jour: "Pratique du jour",
    hub_proactif_quotidien: "quotidien",
    hub_proactif_hebdo: "hebdo",
    hub_proactif_coreg: "Une vraie conversation avec une personne sûre, cette semaine",
    hub_proactif_vide: "Complète le questionnaire pour construire ta garde.",
    hub_ikigai_titre: "Ton offrande — l'Ikigai",
    hub_ikigai_sous: "Ce que ton exilé a cherché toute sa vie est ce que tu es le mieux placé pour offrir.",
    hub_ikigai_quand: "Module de la phase 6 (Action engagée) : à explorer une fois l'exilé rencontré — l'exilé central de ton rapport est {exil}. Avant, ce serait une stratégie de plus.",
    hub_ikigai_archetypes: "Tes archétypes de génie",
    hub_ikigai_activites: "Activités-miroir — goûter l'offrande sans tout bousculer",
    hub_ikigai_piege: "La fausse piste à surveiller :",
    hub_ikigai_theorie: "Lire le chapitre « L'Ikigai — ce pour quoi on se lève » →",
    tendance_homme: "♂ plus souvent rapporté chez les hommes",
    tendance_femme: "♀ plus souvent rapporté chez les femmes",
    tendance_note: "Tendances rapportées — jamais une règle individuelle.",
    ponderation_titre: "Une pondération pour l'ensemble",
    ponderation_sub: "Ces comportements, je les vis plutôt… La fréquence et l'ancienneté affinent le poids de toutes tes reconnaissances.",
    /* le déclencheur — l'épreuve de vérité */
    declencheur_titre: "Le déclencheur — l'épreuve de vérité",
    declencheur_sous: "La parole inverse de la pierre de touche : elle attaque volontairement ta blessure, pour vérifier si l'hypothèse est la bonne. Si elle te touche, le corps reconnaît son exilé. Si elle te laisse froid, c'est une information, pas un verdict.",
    declencheur_consigne: "À faire à froid, jamais en crise, jamais sous l'emprise d'un produit. Tu peux t'arrêter à tout moment.",
    declencheur_consentir: "Je comprends — montrer la parole",
    declencheur_masquer: "Masquer la parole",
    declencheur_choisir: "Parole de :",
    declencheur_observation_titre: "Ce que tu écoutes",
    declencheur_observation: ["Le corps : gorge serrée, poitrine, ventre, larmes", "L'émotion : honte, vide, peur, culpabilité", "L'intensité : de 0 (rien) à 10 (insoutenable)", "La part qui répond : qui parle en toi ?"],
    declencheur_question: "Est-ce que ça a résonné ?",
    declencheur_reponses: { fort: "Oui, fort", peu: "Un peu", non: "Pas du tout" },
    declencheur_interpretation: {
      fort: "Forte résonance — l'hypothèse est probable : cette blessure est bien là, et la parole l'a touchée. Reviens à ta pierre de touche pour la déposer.",
      peu: "Résonance légère — l'hypothèse reste ouverte. Tu peux essayer un autre exilé, ou revenir plus tard.",
      non: "Aucune résonance — ce n'est probablement pas le bon exilé. Ce n'est pas un échec : c'est une information. Essaie un autre exilé."
    },
    declencheur_antidote: "Revenir à ma pierre de touche",
    declencheur_respi: "La respiration 4-7-8",
    declencheur_synthese_titre: "Ta synthèse",
    declencheur_synthese_points: "Points cumulés : {points}/{max}",
    declencheur_synthese_rapport: "Ton rapport plaçait : {liste}.",
    declencheur_synthese_confirme: "La parole confirme ton rapport : {nom} est bien au cœur.",
    declencheur_synthese_ecart: "La parole désigne {nom}, alors que le rapport plaçait {rapport} en tête — l'hypothèse est à réajuster.",
    declencheur_synthese_aucune: "Aucune confirmation pour l'instant : les paroles n'ont pas résonné. Le rapport reste une hypothèse à vérifier.",
    declencheur_synthese_vide: "Réponds à l'auto-évaluation d'au moins une parole : ta synthèse apparaîtra ici.",
    affinage_titre: "Affinage — 3 questions pour préciser ta lecture",
    affinage_sub: "Trois questions rapides, avant ton rapport. Elles affinent le décodage : qui mène vraiment, et quel exilé est au cœur. Si tu ne sais pas, passe — on n'invente pas.",
    affinage_question_prefix: "Question",
    affinage_passer: "Passer cette question",
    affinage_note: "3 questions rapides peuvent préciser ta lecture : qui mène, et quel exilé est au cœur.",
    affinage_cta: "Préciser ma lecture →",
    affinage_refaire: "Affiner mes réponses",
    profils_titre: "Tes profils",
    analyse_nom: "Analyse comportement",
    analyse_sub: "Décoder une combinaison précise — ex. Alcool · A « Je suis nul, je bois pour éteindre la voix qui me le répète ». Découvre la coalition de parts qui la produit : l'exilé qui pousse, le manager qui protège, le pompier qui éteint — et le chemin inverse.",
    analyse_recherche: "Tape : alcool, scroll, colère, fuite…",
    analyse_porte_sous: "Décoder un comportement précis : les parts qui le jouent, ce qu'il protège, le chemin idéal.",
    analyse_coalition: "La coalition — les trois parts en jeu",
    analyse_moteur: "Le moteur", analyse_strategie: "La stratégie", analyse_crise: "La crise",
    profils_sous: "Chaque profil garde ses réponses, son rapport et sa lettre. Choisis-en un ou crées-en un nouveau.",
    profil_nouveau: "Nouveau profil",
    profil_continuer: "Continuer",
    profil_supprimer: "Supprimer",
    profil_confirm_suppression: "Supprimer ce profil ? Ses réponses, son rapport et sa lettre seront perdus.",
    profil_aucun: "Aucun profil pour l'instant.",
    profil_changer: "Changer de profil",
    ans: "ans",
    accueil_titre_nouveau: "Nouveau profil",
    accueil_qui: "Comment t'appelles-tu ?",
    accueil_placeholder: "Ton prénom",
    accueil_tu_es: "Tu es…",
    accueil_age: "Ton âge :",
    accueil_alerte: "Remplis ton prénom, ton profil et ton âge pour commencer.",
    langue_label: "Langue",
    /* libellés partagés (analyse, rapport, fiche, miroir) */
    famille_label: "FAMILLE",
    phase_label: "Phase",
    combinaison_label: "Combinaison",
    phrase_interieure_label: "Phrase intérieure",
    declencheur_label: "Déclencheur",
    protege_label: "Ce que ça protège",
    cout_label: "Coût",
    besoin_vise_label: "Besoin vital dévoyé",
    ideal_label: "Comportement idéal",
    miroir_comportement_label: "Comportement miroir",
    micro_pas_label: "Micro-pas",
    micro_pas_semaine_label: "Micro-pas semaine 1",
    analyse_combo_entete: "Comportement {id} — {nom} · combinaison {lettre}",
    analyse_inconnue: "Combinaison inconnue.",
    analyse_tout_deplier: "Tout déplier", analyse_tout_replier: "Tout replier",
    seq_phases: "<b>Être</b> (Polyvagal — sécuriser) → <b>Sentir</b> (IFS — rencontrer les parts) → <b>Agir</b> (ACT — micro-pas vers les valeurs)",
    scores_exiles: "Exilés", scores_managers: "Managers", scores_pompiers: "Pompiers",
    fiche_blessure: "Blessure", fiche_croyance: "Croyance", fiche_part_desavouee: "Part désavouée",
    fiche_strategie: "Stratégie", fiche_peur: "Peur", fiche_crise: "Crise", fiche_alternative: "Alternative",
    fiche_nouveau_role: "Nouveau rôle", fiche_lieu_corporel: "Lieu corporel",
    fiche_origine: "L'origine (0-7 ans)", fiche_vocabulaire: "Les mots qui reviennent", fiche_morphologie: "Le corps qui parle",
    fiche_signatures: "Signatures", fiche_protecteurs: "Protecteurs", fiche_pompiers: "Pompiers extincteurs",
    chemin_blocage: "Ce qui peut bloquer :",
    miroir_meme_blessure: "— même blessure que toi : « {croyance} ». Elle/il vit sans filtre ce que tu as dû enfermer :",
    miroir_origine_titre: "L'origine : la clé parentale",
    miroir_origine_theorie: "Lire « Les 5 blessures et les 5 masques » (chapitre 4-5) →",
    miroir_triangle_vie_titre: "Le triangle de la vie",
    miroir_triangle_exemple: "L'exemple",
    bilan_soir_titre: "Le bilan du soir",
    bilan_soir_sub: "Le rituel de fin de journée : quelle part a pris le dessus, comment tu t'es senti·e — et le droit de te pardonner.",
    bilan_soir_part_label: "La part qui a pris le dessus aujourd'hui",
    bilan_soir_senti_label: "Comment je me suis senti·e",
    bilan_soir_pardonner: "Je me pardonne — je me donne le droit d'avoir utilisé cette part",
    bilan_soir_vide: "Choisis une part, puis un mot pour ton émotion, puis pardonne-toi.",
    bilan_soir_fait: "Bilan du soir : {part} — {senti}. Pardonne-toi, et demain est un autre jour.",
    bilan_soir_reset: "Recommencer demain",
    affinage_sentis_titre: "Tu ne retrouves pas ton émotion ? D'autres mots pour la dire :",
    declencheur_sentis_titre: "Des mots pour l'émotion",
    miroir_dynamique: "Dynamique d'attachement prédite :",
    miroir_blessure_commune: "Blessure commune :",
    miroir_active: "Ce que B active chez toi :",
    miroir_reveil: "Le réveil :",
    miroir_piege: "Le piège :",
    miroir_en_crise: "En crise :",
    miroir_aucune_paire: "Aucune des 28 paires canoniques ne correspond directement à ton profil — ton miroir est plus singulier. Le calcul ci-dessus reste valable.",
    miroir_indice: "Indice", miroir_vrai: "Vrai miroir", miroir_leurre: "Leurre",
    miroir_stade: "Stade", miroir_piege_court: "Piège :",
    miroir_reponse: "Ta réponse…",
    import_reussi: "Import réussi.",
    import_impossible: "Import impossible : ",
    /* termes des micro-pas → chapitre de théorie (hyperliens) */
    liens_theorie: { "4-7-8": "livre-3/3-2", "orienting": "livre-2/2-1", "ancrage": "livre-3/3-3", "reparentage": "livre-4/4-4", "respiration": "livre-3/3-2" }
  };

  var STR_EN = {
    app_nom: "Healing — meeting yourself",
    tagline: "A behavior is never the problem. It is the solution a child once found to survive.",
    nav: { guide: "Discover", accueil: "Home", comportements: "Questionnaire", rapport: "Report", hub: "Path", engagements: "Commitments", miroir: "Mirror", theorie: "Theory", compatibilite: "Compatibility" },
    guide: {
      titre: "Welcome. How it works.",
      sous: "Three minutes to understand — then it's up to you.",
      ideet: "The idea in one sentence",
      idee: "When you do something that hurts you — drinking, scrolling, running away, putting yourself down, pleasing others — it is not a flaw. It is a solution your system once found to survive. This app helps you see who, inside you, is still playing that solution… and to offer them another way.",
      partst: "Your inner team — 3 words worth knowing",
      partss: "In this app we talk about \"parts\": small voices inside you, each with a role.",
      exile: "The Exile — the engine",
      exiled: "The wounded child part. It carries shame, emptiness, the fear of being left. It is what drives the behavior.",
      manager: "The Manager — the strategy",
      managerd: "The part that manages before the crisis: the Critic, the Perfectionist, the Rescuer… It organizes so the Exile never suffers.",
      pompier: "The Firefighter — the crisis",
      pompierd: "The emergency part that puts out the fire during the crisis: the Fleer, the Drinker, the Scroller… It acts fast, hard, without thinking.",
      coalition: "Golden rule: a behavior is never played by a single part. It is always a trio: Exile × Manager × Firefighter.",
      mille: "And one system, a thousand symptoms: all your behaviors connect to the same signature. We never treat an isolated symptom.",
      parcourst: "The journey, step by step",
      parcourss: "Everything can be changed, nothing is graded, nothing is judged. \"Nothing is a fault: everything is a clue.\"",
      e1t: "Create a profile", e1d: "First name, gender, age, two boxes to tick. That's all. You can create several — one for you, one to compare.",
      e2t: "Take stock", e2d: "The questionnaire \"What feels like you\": 9 families of behaviors, with search. Simple mode: about 2 minutes. Detailed mode: precise signs for a finer report. Tick what speaks to you, honestly.",
      e3t: "3 precision questions", e3d: "The refinement: three quick questions before the report. You can skip any question — we never invent in your place.",
      e4t: "Read your report", e4d: "Five sections: your inventory, the decoding of each behavior, your system signature (with your constellation map), your path toward the ideal behavior, and your touchstone — a few words for you.",
      e5t: "Follow your path", e5d: "The \"Your path\" hub: your personalized touchstone, the commitments letter, the mirror — who triggers you and why.",
      etapes_note: "Real durations: simple mode ≈ 2 min, detailed mode ≈ 10–15 min.",
      libret: "Without a profile, you can already explore",
      libres: "Three doors are open, even before you start:",
      libre_analyse: "Analyze a behavior", libre_analyse_d: "Decode any behavior, no questionnaire needed.",
      libre_theorie: "Read the theory", libre_theorie_d: "The complete system: 13 books, 55 chapters, a glossary.",
      libre_compat: "Compare two profiles", libre_compat_d: "Two people face to face: what each one triggers in the other.",
      criset: "The ♥ button \"I'm not okay\"",
      crise: "It is on every page. It analyzes nothing: it puts out the fire. Guided 4-7-8 breathing, emergency numbers, and the advice not to decide anything important today.",
      ethiquet: "What this app is not",
      ethique: "Not medical advice, not a diagnosis, not a therapist. Every reading is a hypothesis to check with you, never a verdict. And everything stays on your device: no data leaves your browser — no AI, no account, no network.",
      cta: "Get started",
      cta_sous: "or explore freely — the top bar is always there."
    },
    hub_portrait: "The portrait", hub_portrait_sous: "You, daily and in crisis — read from your system",
    portrait: {
      titre: "Your portrait — daily life and crisis",
      sub: "{nom}, read from your system: {m} managers, {p} firefighters, {e} exiles at the core.",
      disclaimer: "A probable portrait, not a verdict. Every line is a concrete hypothesis: keep what resonates, correct what doesn't fit you.",
      crise_btn: "If the crisis is here right now: don't read this portrait — go to the ♥ button first.",
      q_titre: "Daily life",
      q_sous: "What your managers — and sometimes your exiles — do to your ordinary life.",
      bascule_titre: "The tipping point — when daily life cracks",
      bascule_sous: "Every manager has a breaking point: the firefighter they collapse into, and what lights it.",
      derive_tpl: "In daily life, {manager}: {strategie}. When it cracks, it collapses into {pompier}: {crise}.",
      derive_alt: "The alternative: {alt}",
      k_titre: "Your virtuous roles",
      k_sous: "Karpman's Drama Triangle read through your parts — and their virtuous conversion (chapter 10-13).",
      k_managers: "Your dominant managers",
      k_pompiers: "Your firefighters in crisis",
      k_converti: "Conversion:",
      k_pivot: "Pivot question:",
      k_theorie: "Read “The Empowerment Triangle: Creator, Challenger, Coach” →",
      c_titre: "In crisis",
      c_sous: "What your firefighters do to your life when the system ignites.",
      b_titre: "The need underneath",
      b_sous: "The exiles at the center: what they believe, what they seek, what they need.",
      declencheurs_titre: "Your triggers",
      miroir_titre: "Your mirror — what triggers you",
      miroir_ligne: "{nom} — {croyance}",
      miroir_paires: "What triggers you in others: {noms}",
      miroir_lien: "See the full mirror →",
      eteint: "It extinguishes: {noms}",
      contraire: "Its opposite: {texte}",
      rien: "Nothing salient detected for this dimension — that is information, not a void.",
      dim: {
        alimentation: "Eating", sport: "Sport", travail: "Work", rythme: "Rhythm",
        social: "Social", famille: "Family", relations: "Relationships", valeurs: "Values", besoins: "Needs"
      }
    },
    btns: { commencer: "Start →", rapport: "See my report", imprimer: "Print", exporter_md: "Export .md", exporter_json: "Export my session", importer: "Import", effacer: "Erase everything", modifier: "Edit", pause: "Pause — I'll come back later", revenir: "Back", continuer: "Continue →" },
    familles_intro: "Check what feels like you, honestly. You can change anything. Nothing is a fault: everything is a clue.",
    famille_averti: "This part talks about desire, blocks and sexual strategies. You can skip it and come back to it.",
    famille_averti_auto: "This part covers behaviors that hurt the body. Checking them is not a diagnosis — but if you hurt yourself, you deserve to be accompanied. In France, a helpline: 3114 (free, 24/7). You can skip this family and come back to it.",
    q_titre: "What feels like you",
    frequence_label: "Frequency",
    frequences: { quotidien: "Daily", hebdomadaire: "Weekly", en_crise: "In crisis", rare: "Rare" },
    depuis_label: "Since",
    depuiss: { enfance: "Childhood", adolescence: "Teenage years", adulte: "Adulthood" },
    signes_label: "Do these examples speak to you? Tick the ones that resonate — it counts as \"I recognize myself\" (broad reading, reduced weight). For full weight, tick a precise combination below.",
    recherche_placeholder: "Type: scroll, money, anger, escape…",
    cochés: "checked",
    rien_coché: "Nothing checked yet — and that is already an answer.",
    reconnaissances: "broad recognition(s)",
    deja_detaillees: "detailed combination(s) already checked — they still count",
    mode_simple: "Simple",
    mode_simple_sous: "Categories and “I recognize myself” — about 2 minutes",
    mode_exhaustif: "Detailed",
    mode_exhaustif_sous: "Specific signs and part combinations — a finer report",
    note_large: "Broad reading: you recognized categories without specifying combinations. For a finer report, switch to the detailed questionnaire.",
    note_large_cta: "Switch to detailed",
    combinaisons_cochees: "combination(s) checked",
    declencheur_prefix: "Trigger: ",
    pdt_titre: "THE TOUCHSTONE",
    pdt_pourquoi: "Why these words?",
    regles_titre: "The strict rules",
    regles_confirm: "I have read these rules — they frame my commitments.",
    signature_titre: "Your system signature",
    cycle_titre: "The cycle that keeps you spinning",
    symptomes_titre: "One system, a thousand symptoms",
    enfance_titre: "The childhood decision (hypothesis)",
    rapport_codes_lien: "Understand how a protection becomes a prison — the Codes (chapter 11-11) →",
    chemin_titre: "Your path, from Actual to Ideal",
    rapport_vertueux_lien: "My virtuous roles — my parts' Drama Triangle (Portrait page) →",
    decode_titre: "The decoding: behaviors → combinations of parts",
    inventaire_titre: "What you checked",
    scores_titre: "Your parts' scores",
    scores_note: "These are readings, not verdicts. To be checked with you.",
    familles_touchees: "Families affected: ",
    rapport_simple: {
      titre: "Simple report",
      sous: "The essentials of your report — your signature, your path, your touchstone.",
      btn: "Simple report",
      sous_btn: "the essentials, without the diagrams",
      exiles: "Exile(s) at the core",
      managers: "Dominant managers",
      pompiers: "Go-to firefighters",
      declencheurs: "Triggers",
      couts: "What it costs",
      inventaire: "{n} combination(s) checked — families affected: {f}.",
      chemin_vide: "No key behavior for now."
    },
    seq_obligatoire: "Mandatory sequence:",
    hub_titre: "{nom}, your report is here whenever you want.",
    hub_intro: "Three paths now. Take your time.",
    hub_engagements: "Commitments", hub_engagements_sous: "The letter to yourself — to print, to reread",
    hub_miroir: "Theoretical mirror", hub_miroir_sous: "Who triggers me — and why",
    hub_theorie: "Theory", hub_theorie_sous: "Understand the whole system",
    miroir_titre: "Your theoretical mirror",
    miroir_formule: "Same wound + opposite strategy + carried disowned part",
    miroir_noms: {
      invisible: "The Free Existence", humilie: "The Unassailable Dignity", abandonne: "The Presence That Stays",
      terrifie: "Safety Embodied", coupable: "Innocence Granted", parentifie: "Vulnerability Embraced"
    },
    miroir_paires: "The pairs that concern you",
    miroir_triangle_titre: "The triangle you play together",
    miroir_triangle_tes: "Your parts play",
    miroir_triangle_ses: "their parts play",
    miroir_triangle_theorie: "Virtuous conversion: chapter 10-13 →",
    miroir_stades: "The 4 stages of awakening",
    miroir_garde: "True mirror or lure?",
    miroir_4q: "The 5 mirror questions",
    miroir_4q_sub: "Answer freely — the first 4 come from the founding text « Awakening Trigger ». The 5th is IFS's magic question: it turns the projection into a doorway toward the Exile.",
    miroir_decodage_titre: "Decoding projections",
    miroir_decodage_sous: "Carl Jung's heritage translated into IFS: every visceral reaction is a door into the Shadow.",
    miroir_decodage_col_reaction: "If I react like this…",
    miroir_decodage_col_type: "It is a projection of…",
    miroir_decodage_col_ombre: "What is locked in the Shadow (to reintegrate)",
    miroir_decodage_col_cle: "The clue",
    miroir_pdt_titre: "THE TOUCHSTONE — mirror",
    compat_porte_sous: "Two profiles face to face, the mirror between them",
    compat_sub: "The mirror applied to two systems: what each one triggers in the other.",
    compat_taux_titre: "Mirror echo score",
    compat_taux_sous: "Two laws, one mechanism: same wound (resonance) + opposite strategy (complementarity) + disowned part lived without shame.",
    compat_taux_resonance: "Resonance — same wound",
    compat_taux_complementarite: "Complementarity — opposite strategy",
    compat_taux_desavouee: "Disowned part — lived without shame",
    compat_taux_seuil_faible: "Weak echo: the two systems barely intersect.",
    compat_taux_seuil_marque: "Marked echo: your shadows answer each other — this is ground to work on.",
    compat_taux_seuil_intense: "Intense echo: your shadows seek each other. This mirror is a powerful lever.",
    compat_peu_profils: "You need at least two profiles to compare. Create a second profile from the home page.",
    compat_pas_de_donnees: "— questionnaire not filled",
    compat_managers: "Dominant managers",
    compat_pompiers: "Firefighter parts",
    compat_choisir_a: "Profile A",
    compat_choisir_b: "Profile B",
    compat_blessure_titre: "The wound",
    compat_blessure_oui: "Shared exiles at the core — you carry the same wound: {noms} ({croyance})",
    compat_blessure_oui_risque: "You understand each other without words. Risk: nobody sees the elephant, the system reinforces itself.",
    compat_blessure_non: "Different wounds: {a} / {b}",
    compat_blessure_non_texte: "You don't speak the same language of wounds. The mirror activates by contrast: what one lacks, the other carries.",
    compat_aucune_blessure: "No exile detected (empty questionnaire).",
    compat_aussi: "also: ",
    compat_danses_titre: "Crossed mirror dances",
    compat_mindmap_titre: "Mindmap of both systems",
    compat_danses_sub: "The mirror pairs where your two systems meet.",
    compat_attraction: "{a} does {profil_a} (via {viaA}) — {b} carries the mirror: {miroir_b} (via {viaB})",
    compat_meme_role: "Same role in the same dance — {a} via {viaA}, {b} via {viaB}: {profil_a}",
    compat_aucune_danse: "No mirror pair crosses these two systems.",
    compat_langages_titre: "How the other expects apologies",
    compat_langages_sous: "Based on their dominant parts:",
    compat_langages_vide: "Complete this profile's questionnaire to find out.",
    compat_attachement_titre: "The attachment dance",
    compat_attachement_evitant: "Avoidant ↔ Preoccupied",
    compat_attachement_fuyards: "Two avoidants: each withdraws, nobody pursues. The lack settles in silence.",
    compat_attachement_poursuivants: "Two preoccupied: intensity without withdrawal. Anxiety rises fast, demands overflow.",
    compat_attachement_chaos: "Disorganized at play — approach-flee:",
    compat_attachement_aucun: "No dominant attachment style detected.",
    compat_projections_titre: "Crossed projections",
    compat_projections_sous: "What each one projects onto the other — the golden rule: what irritates or fascinates me in the other is a part of myself I do not know yet.",
    compat_proj_vers: "{a} projects onto {b}",
    compat_proj_ombre_managers: "Dark shadow — the Manager judges in the other what it exiled:",
    compat_proj_ombre_pompiers: "Dark shadow — in crisis, the Firefighter will see a threat:",
    compat_proj_or: "Golden shadow — the gold the Exile delegates:",
    theorie_recherche: "Search the theory…",
    theorie_titre: "Theory — the Triaxial System",
    theorie_lus: "read",
    quand_label: "When:",
    engagements_titre: "Commitments — the letter to yourself",
    engagements_sub: "Each commitment turns an identified pattern into an observable gesture. You can rephrase, remove, add — it is YOUR letter.",
    rapport_titre_prefix: "REVERSE BEHAVIOR — ",
    wipe_confirm: "Erase everything? This is final. You can export your session first.",
    wipe_done: "Everything erased. This page kept nothing.",
    partielle: "Partial reading — complete your questionnaire whenever you want.",
    clique_carte: "Exile at the center — Managers who protect — Firefighters who extinguish. Click a circle to see its sheet.",
    clique_cycle: "Click a cycle station to read it.",
    cycle_selecteur: "View the cycle from:",
    signature_selecteur: "View the detail of:",
    carte_selecteur: "View the map of:",
    carte_globale_titre: "Your parts constellation",
    carte_globale_legende: "Overview — the 3 dominant exiles in the center, the managers who protect and the firefighters who extinguish around them. Click a circle to see its sheet.",
    carte_vue_label: "Show:",
    carte_vue_globale: "Constellation — overview",
    signature_vue_label: "View:",
    signature_vue_recit: "Story",
    signature_vue_fiche: "Detailed sheet",
    pdt_selecteur: "Touchstone for:",
    chemin_selecteur: "Sequence step:",
    constellation_plein_ecran: "Fullscreen",
    constellation_fermer: "Close",
    clique_chemin: "Click a waypoint to see what happens there.",
    /* personalised card (3 exiles) + crisis mode + simple-mode weighting */
    pdt_carte_titre: "My touchstone",
    pdt_carte_sous: "A personalized word, built from your {n} main exiles — {noms}.",
    crise_btn: "I'm not OK",
    crise_titre: "I'm not OK",
    crise_sub: "We don't analyze anything: we put out the fire. Your system is on alert — this is not the time to understand, it is the time to secure.",
    crise_consigne: "Do not decide anything important today. A system on alert makes no good decisions.",
    crise_respi_titre: "The 4-7-8 breathing",
    crise_respi_etapes: "Inhale through the nose for 4 seconds — Hold for 7 seconds — Exhale through the mouth for 8 seconds",
    crise_respi_conseil: "Repeat 4 cycles. If you can, place one hand on your belly and one on your heart.",
    crise_urgence_titre: "If this is an emergency",
    crise_liens_titre: "When your body calms down",
    crise_liens_texte: "Two protocols from the theory, once your breath has come back:",
    miroir_micro_titre: "The awakening in micro-steps — check them when done",
    miroir_micro_compat: "Awakening micro-steps",
    miroir_boucles: "Interaction loops",
    miroir_boucle_cycle: "The ping-pong",
    miroir_boucle_sortie: "How to break the loop",
    conflit_titre: "What this behavior triggers in others",
    conflit_danse: "The predictable dance:",
    conflit_lien: "See the pair in the Mirror →",
    arret_label: "In the moment",
    hub_arret_titre: "I feel like…",
    hub_arret_sub: "Choose a behavior — the immediate stop protocol shows up.",
    hub_langages_titre: "My main love languages",
    hub_langages_sous: "Based on your dominant parts — how to feed them.",
    hub_langages_vide: "Complete the questionnaire to discover your languages.",
    hub_proactif_titre: "My proactive guard",
    hub_proactif_sous: "The trigger is cut the day before, not in the moment. Check what you did today.",
    hub_proactif_du_jour: "Practice of the day",
    hub_proactif_quotidien: "daily",
    hub_proactif_hebdo: "weekly",
    hub_proactif_coreg: "One real conversation with a safe person, this week",
    hub_proactif_vide: "Complete the questionnaire to build your guard.",
    hub_ikigai_titre: "Your offering — Ikigai",
    hub_ikigai_sous: "What your Exile has been seeking all its life is what you are best placed to offer.",
    hub_ikigai_quand: "Phase 6 module (Committed Action): explore it once the Exile has been met — your central Exile is {exil}. Before that, it would be one more strategy.",
    hub_ikigai_archetypes: "Your genius archetypes",
    hub_ikigai_activites: "Mirror activities — taste the offering without turning everything upside down",
    hub_ikigai_piege: "The false trail to watch for:",
    hub_ikigai_theorie: "Read the chapter “Ikigai: what you get up for” →",
    tendance_homme: "♂ more often reported in men",
    tendance_femme: "♀ more often reported in women",
    tendance_note: "Reported trends — never an individual rule.",
    ponderation_titre: "One weighting for the whole set",
    ponderation_sub: "These behaviors, I mostly experience them… Frequency and how long they have been there sharpen the weight of all your recognitions.",
    /* the trigger — the truth test */
    declencheur_titre: "The trigger — the truth test",
    declencheur_sous: "The reverse of the touchstone: it deliberately attacks your wound, to check whether the hypothesis is right. If it touches you, your body recognizes its exile. If it leaves you cold, that is information, not a verdict.",
    declencheur_consigne: "Do this when calm, never in crisis, never under the influence. You can stop at any time.",
    declencheur_consentir: "I understand — show the words",
    declencheur_masquer: "Hide the words",
    declencheur_choisir: "Words for:",
    declencheur_observation_titre: "What you listen for",
    declencheur_observation: ["The body: tight throat, chest, belly, tears", "The emotion: shame, emptiness, fear, guilt", "The intensity: from 0 (nothing) to 10 (unbearable)", "The part that answers: who is speaking in you?"],
    declencheur_question: "Did it resonate?",
    declencheur_reponses: { fort: "Yes, strongly", peu: "A little", non: "Not at all" },
    declencheur_interpretation: {
      fort: "Strong resonance — the hypothesis is likely: the wound is real, and the words touched it. Come back to your touchstone to put it down.",
      peu: "Slight resonance — the hypothesis stays open. You can try another exile, or come back later.",
      non: "No resonance — this is probably not the right exile. It is not a failure: it is information. Try another exile."
    },
    declencheur_antidote: "Back to my touchstone",
    declencheur_respi: "The 4-7-8 breathing",
    declencheur_synthese_titre: "Your summary",
    declencheur_synthese_points: "Cumulative points: {points}/{max}",
    declencheur_synthese_rapport: "Your report ranked: {liste}.",
    declencheur_synthese_confirme: "The words confirm your report: {nom} is indeed at the core.",
    declencheur_synthese_ecart: "The words point to {nom}, while your report ranked {rapport} first — the hypothesis needs adjusting.",
    declencheur_synthese_aucune: "No confirmation yet: the words did not resonate. The report remains a hypothesis to check.",
    declencheur_synthese_vide: "Answer the self-assessment for at least one word: your summary will appear here.",
    affinage_titre: "Refinement — 3 questions to sharpen your reading",
    affinage_sub: "Three quick questions, before your report. They refine the decoding: who really leads, and which exile is at the core. If you don't know, skip — we don't invent.",
    affinage_question_prefix: "Question",
    affinage_passer: "Skip this question",
    affinage_note: "3 quick questions can sharpen your reading: who leads, and which exile is at the core.",
    affinage_cta: "Sharpen my reading →",
    affinage_refaire: "Refine my answers",
    profils_titre: "Your profiles",
    analyse_nom: "Behavior analysis",
    analyse_sub: "Decode a precise combination — e.g. Alcohol · A “I'm worthless, I drink to silence the voice that keeps telling me so.” Discover the coalition of parts producing it: the exile that drives, the manager that protects, the firefighter that extinguishes — and the reverse path.",
    analyse_recherche: "Type: alcohol, scroll, anger, escape…",
    analyse_porte_sous: "Decode a specific behavior: the parts at play, what it protects, the ideal path.",
    analyse_coalition: "The coalition — the three parts at play",
    analyse_moteur: "The engine", analyse_strategie: "The strategy", analyse_crise: "The crisis",
    profils_sous: "Each profile keeps its answers, its report and its letter. Choose one or create a new one.",
    profil_nouveau: "New profile",
    profil_continuer: "Continue",
    profil_supprimer: "Delete",
    profil_confirm_suppression: "Delete this profile? Its answers, report and letter will be lost.",
    profil_aucun: "No profile yet.",
    profil_changer: "Switch profile",
    ans: "yrs",
    accueil_titre_nouveau: "New profile",
    accueil_qui: "What's your name?",
    accueil_placeholder: "Your first name",
    accueil_tu_es: "You are…",
    accueil_age: "Your age:",
    accueil_alerte: "Fill in your name, profile and age to start.",
    langue_label: "Language",
    /* shared labels (analyse, report, sheet, mirror) */
    famille_label: "FAMILY",
    phase_label: "Phase",
    combinaison_label: "Combination",
    phrase_interieure_label: "Inner phrase",
    declencheur_label: "Trigger",
    protege_label: "What it protects",
    cout_label: "Cost",
    besoin_vise_label: "Diverted vital need",
    ideal_label: "Ideal behavior",
    miroir_comportement_label: "Mirror behavior",
    micro_pas_label: "Micro-steps",
    micro_pas_semaine_label: "Micro-steps week 1",
    analyse_combo_entete: "Behavior {id} — {nom} · combination {lettre}",
    analyse_inconnue: "Unknown combination.",
    analyse_tout_deplier: "Expand all", analyse_tout_replier: "Collapse all",
    seq_phases: "<b>Be</b> (Polyvagal — secure) → <b>Feel</b> (IFS — meet the parts) → <b>Act</b> (ACT — micro-steps toward values)",
    scores_exiles: "Exiles", scores_managers: "Managers", scores_pompiers: "Firefighters",
    fiche_blessure: "Wound", fiche_croyance: "Belief", fiche_part_desavouee: "Disowned part",
    fiche_strategie: "Strategy", fiche_peur: "Fear", fiche_crise: "Crisis", fiche_alternative: "Alternative",
    fiche_nouveau_role: "New role", fiche_lieu_corporel: "Body location",
    fiche_origine: "Origin (0-7 years)", fiche_vocabulaire: "The words that come back", fiche_morphologie: "The body that speaks",
    fiche_signatures: "Signatures", fiche_protecteurs: "Protectors", fiche_pompiers: "Extinguishing firefighters",
    chemin_blocage: "What can block:",
    miroir_meme_blessure: "— same wound as you: “{croyance}”. They live without filter what you had to lock away:",
    miroir_origine_titre: "The origin: the parental key",
    miroir_origine_theorie: "Read “The 5 wounds and the 5 masks” (chapter 4-5) →",
    miroir_triangle_vie_titre: "The triangle of life",
    miroir_triangle_exemple: "The example",
    bilan_soir_titre: "The evening review",
    bilan_soir_sub: "The end-of-day ritual: which part took over, how you felt — and the right to forgive yourself.",
    bilan_soir_part_label: "The part that took over today",
    bilan_soir_senti_label: "How I felt",
    bilan_soir_pardonner: "I forgive myself — I give myself the right to have used this part",
    bilan_soir_vide: "Choose a part, then a word for your emotion, then forgive yourself.",
    bilan_soir_fait: "Evening review: {part} — {senti}. Forgive yourself, and tomorrow is another day.",
    bilan_soir_reset: "Start over tomorrow",
    affinage_sentis_titre: "Can't find your emotion? Other words for it:",
    declencheur_sentis_titre: "Words for the emotion",
    miroir_dynamique: "Predicted attachment dynamic:",
    miroir_blessure_commune: "Shared wound:",
    miroir_active: "What B activates in you:",
    miroir_reveil: "The awakening:",
    miroir_piege: "The trap:",
    miroir_en_crise: "In crisis:",
    miroir_aucune_paire: "None of the 28 canonical pairs directly matches your profile — your mirror is more singular. The calculation above still stands.",
    miroir_indice: "Clue", miroir_vrai: "True mirror", miroir_leurre: "Lure",
    miroir_stade: "Stage", miroir_piege_court: "Trap:",
    miroir_reponse: "Your answer…",
    import_reussi: "Import successful.",
    import_impossible: "Import failed: ",
    /* micro-step terms → theory chapter (hyperlinks) */
    liens_theorie: { "4-7-8": "livre-3/3-2", "orienting": "livre-2/2-1", "grounding": "livre-3/3-3", "reparenting": "livre-4/4-4", "breathing": "livre-3/3-2" }
  };

  var STR_ES = {
    app_nom: "Healing — encontrarse a uno mismo",
    tagline: "La conducta nunca es el problema. Es la solución que un niño encontró para sobrevivir.",
    nav: { guide: "Descubrir", accueil: "Inicio", comportements: "Cuestionario", rapport: "Informe", hub: "Camino", engagements: "Compromisos", miroir: "Espejo", theorie: "Teoría", compatibilite: "Compatibilidad" },
    guide: {
      titre: "Bienvenido. Cómo funciona.",
      sous: "Tres minutos para entenderlo — luego tú decides.",
      ideet: "La idea en una frase",
      idee: "Cuando haces algo que te hace daño — beber, hacer scroll, huir, rebajarte, complacer — no es un defecto. Es una solución que tu sistema encontró un día para sobrevivir. Esta app te ayuda a ver quién, dentro de ti, sigue jugando esa solución… y a ofrecerle otro camino.",
      partst: "Tu equipo interior — 3 palabras que conviene saber",
      partss: "En esta app hablamos de «partes»: pequeñas voces dentro de ti, cada una con un papel.",
      exile: "El Exiliado — el motor",
      exiled: "La parte de infancia herida. Carga la vergüenza, el vacío, el miedo a que te abandonen. Es quien empuja la conducta.",
      manager: "El Manager — la estrategia",
      managerd: "La parte que gestiona antes de la crisis: el Crítico, el Perfeccionista, el Salvador… Organiza para que el Exiliado no sufra.",
      pompier: "El Bombero — la crisis",
      pompierd: "La parte de urgencia que apaga durante la crisis: el Fugitivo, el Bebedor, el Scroll… Actúa rápido, fuerte, sin pensar.",
      coalition: "Regla de oro: una conducta nunca la juega una sola parte. Siempre es un trío: Exiliado × Manager × Bombero.",
      mille: "Y un sistema, mil síntomas: todas tus conductas se conectan con la misma firma. Nunca se trata un síntoma aislado.",
      parcourst: "El recorrido, paso a paso",
      parcourss: "Todo se puede modificar, nada se califica, nada se juzga. «Nada es una falta: todo es una pista.»",
      e1t: "Crea un perfil", e1d: "Nombre, género, edad, dos casillas que marcar. Eso es todo. Puedes crear varios — uno para ti, uno para comparar.",
      e2t: "Haz el inventario", e2d: "El cuestionario «Lo que te resuena»: 9 familias de conductas, con búsqueda. Modo simple: unos 2 minutos. Modo exhaustivo: signos precisos para un informe más fino. Marca lo que te hable, con honestidad.",
      e3t: "3 preguntas de precisión", e3d: "El afinado: tres preguntas rápidas antes del informe. Puedes saltar cualquier pregunta — nunca inventamos por ti.",
      e4t: "Lee tu informe", e4d: "Cinco secciones: tu inventario, el descifrado de cada conducta, tu firma de sistema (con el mapa de tu constelación), tu camino hacia la conducta ideal, y tu piedra de toque — unas palabras para ti.",
      e5t: "Sigue tu camino", e5d: "El centro «Tu camino»: tu piedra de toque personalizada, la carta de compromisos, el espejo — quién te activa y por qué.",
      etapes_note: "Duración real: modo simple ≈ 2 min, modo exhaustivo ≈ 10–15 min.",
      libret: "Sin perfil, ya puedes explorar",
      libres: "Tres puertas están abiertas, incluso antes de empezar:",
      libre_analyse: "Analizar una conducta", libre_analyse_d: "Descifra cualquier conducta, sin cuestionario.",
      libre_theorie: "Leer la teoría", libre_theorie_d: "El sistema completo: 13 libros, 55 capítulos, un glosario.",
      libre_compat: "Comparar dos perfiles", libre_compat_d: "Dos personas cara a cara: lo que cada una activa en la otra.",
      criset: "El botón ♥ «No estoy bien»",
      crise: "Está en todas las páginas. No analiza nada: apaga. Respiración guiada 4-7-8, números de emergencia y el consejo de no decidir nada importante hoy.",
      ethiquet: "Lo que esta app no es",
      ethique: "Ni un consejo médico, ni un diagnóstico, ni un psicólogo. Cada lectura es una hipótesis a verificar contigo, nunca un veredicto. Y todo queda en tu dispositivo: ningún dato sale de tu navegador — sin IA, sin cuenta, sin red.",
      cta: "Empezar",
      cta_sous: "o explora libremente — la barra superior siempre está ahí."
    },
    hub_portrait: "El retrato", hub_portrait_sous: "Tú, en el día a día y en crisis — leído desde tu sistema",
    portrait: {
      titre: "Tu retrato — día a día y crisis",
      sub: "{nom}, leído desde tu sistema: {m} managers, {p} bomberos, {e} exiliados en el centro.",
      disclaimer: "Un retrato probable, no un veredicto. Cada línea es una hipótesis concreta: quédate con lo que resuena, corrige lo que no se parece a ti.",
      crise_btn: "Si la crisis está aquí ahora: no leas este retrato — ve primero al botón ♥.",
      q_titre: "En el día a día",
      q_sous: "Lo que tus managers — y a veces tus exiliados — hacen con tu vida ordinaria.",
      bascule_titre: "El punto de quiebre — cuando el día a día se resquebraja",
      bascule_sous: "Cada manager tiene su punto de ruptura: el bombero en el que derrapa, y lo que lo enciende.",
      derive_tpl: "En el día a día, {manager}: {strategie}. Cuando se resquebraja, derrapa hacia {pompier}: {crise}.",
      derive_alt: "La alternativa: {alt}",
      k_titre: "Tus roles virtuosos",
      k_sous: "El Triángulo Dramático de Karpman leído desde tus partes — y su conversión virtuosa (capítulo 10-13).",
      k_managers: "Tus managers dominantes",
      k_pompiers: "Tus bomberos en crisis",
      k_converti: "Conversión:",
      k_pivot: "Pregunta pivote:",
      k_theorie: "Leer « El Triángulo del Empoderamiento: Creador, Retador, Coach » →",
      c_titre: "En crisis",
      c_sous: "Lo que tus bomberos hacen con tu vida cuando el sistema arde.",
      b_titre: "La necesidad debajo de todo",
      b_sous: "Los exiliados en el centro: qué creen, qué buscan, qué necesitan.",
      declencheurs_titre: "Tus detonantes",
      miroir_titre: "Tu espejo — quién te activa",
      miroir_ligne: "{nom} — {croyance}",
      miroir_paires: "Lo que te activa en los demás: {noms}",
      miroir_lien: "Ver el espejo completo →",
      eteint: "Apaga: {noms}",
      contraire: "Su contrario: {texte}",
      rien: "Nada destacable detectado en esta dimensión — es información, no un vacío.",
      dim: {
        alimentation: "Alimentación", sport: "Deporte", travail: "Trabajo", rythme: "Ritmo",
        social: "Social", famille: "Familia", relations: "Relaciones", valeurs: "Valores", besoins: "Necesidades"
      }
    },
    btns: { commencer: "Empezar →", rapport: "Ver mi informe", imprimer: "Imprimir", exporter_md: "Exportar .md", exporter_json: "Exportar mi sesión", importer: "Importar", effacer: "Borrar todo", modifier: "Editar", pause: "Pausa — volveré más tarde", revenir: "Volver", continuer: "Continuar →" },
    familles_intro: "Marca lo que te resuena, con honestidad. Puedes cambiarlo todo. Nada es una falta: todo es una pista.",
    famille_averti: "Esta parte habla de deseo, bloqueos y estrategias sexuales. Puedes saltarla y volver a ella.",
    famille_averti_auto: "Esta parte trata comportamientos que dañan el cuerpo. Marcarlos no es un diagnóstico — pero si te haces daño, tienes derecho a ser acompañado/a. En Francia, una línea de escucha: 3114 (gratuita, 24 h). Puedes saltar esta familia y volver a ella.",
    q_titre: "Lo que te resuena",
    frequence_label: "Frecuencia",
    frequences: { quotidien: "Diario", hebdomadaire: "Semanal", en_crise: "En crisis", rare: "Raro" },
    depuis_label: "Desde",
    depuiss: { enfance: "La infancia", adolescence: "La adolescencia", adulte: "La adultez" },
    signes_label: "¿Te suenan estos ejemplos? Marca los que resuenan: cuenta como \"me reconozco\" (lectura amplia, peso reducido). Para peso completo, marca una combinación precisa abajo.",
    recherche_placeholder: "Escribe: scroll, dinero, ira, huida…",
    cochés: "marcados",
    rien_coché: "Nada marcado por ahora — y eso ya es una respuesta.",
    reconnaissances: "reconocimiento(s) amplio(s)",
    deja_detaillees: "combinación(es) detallada(s) ya marcadas — siguen contando",
    mode_simple: "Simple",
    mode_simple_sous: "Las categorías y «me reconozco» — unos 2 minutos",
    mode_exhaustif: "Exhaustivo",
    mode_exhaustif_sous: "Los signos precisos y las combinaciones de partes — un informe más fino",
    note_large: "Lectura amplia: reconociste categorías sin precisar combinaciones. Para un informe más fino, cambia al cuestionario exhaustivo.",
    note_large_cta: "Cambiar a exhaustivo",
    combinaisons_cochees: "combinación(es) marcada(s)",
    declencheur_prefix: "Detonante: ",
    pdt_titre: "LA PIEDRA DE TOQUE",
    pdt_pourquoi: "¿Por qué estas palabras?",
    regles_titre: "Las reglas estrictas",
    regles_confirm: "He leído estas reglas — enmarcan mis compromisos.",
    signature_titre: "Tu firma de sistema",
    cycle_titre: "El ciclo que te hace girar",
    symptomes_titre: "Un sistema, mil síntomas",
    enfance_titre: "La decisión de infancia (hipótesis)",
    rapport_codes_lien: "Comprender cómo una protección se vuelve prisión — los Códigos (capítulo 11-11) →",
    chemin_titre: "Tu camino, del Actual al Ideal",
    rapport_vertueux_lien: "Mis roles virtuosos — el Triángulo Dramático de mis partes (página Retrato) →",
    decode_titre: "El descifrado: conductas → combinaciones de partes",
    inventaire_titre: "Lo que marcaste",
    scores_titre: "Las puntuaciones de tus partes",
    scores_note: "Son lecturas, no veredictos. A verificar contigo.",
    familles_touchees: "Familias afectadas: ",
    rapport_simple: {
      titre: "Informe simple",
      sous: "Lo esencial de tu informe — tu firma, tu camino, tu piedra de toque.",
      btn: "Informe simple",
      sous_btn: "lo esencial, sin los diagramas",
      exiles: "Exiliado(s) en el centro",
      managers: "Managers dominantes",
      pompiers: "Bomberos de emergencia",
      declencheurs: "Detonantes",
      couts: "Lo que cuesta",
      inventaire: "{n} combinación(es) marcada(s) — familias afectadas: {f}.",
      chemin_vide: "Ningún comportamiento clave por ahora."
    },
    seq_obligatoire: "Secuencia obligatoria:",
    hub_titre: "{nom}, tu informe está aquí cuando quieras.",
    hub_intro: "Tres caminos ahora. Tómate tu tiempo.",
    hub_engagements: "Compromisos", hub_engagements_sous: "La carta a ti mismo — para imprimir, para releer",
    hub_miroir: "Espejo teórico", hub_miroir_sous: "Quién me activa — y por qué",
    hub_theorie: "Teoría", hub_theorie_sous: "Comprender el sistema completo",
    miroir_titre: "Tu espejo teórico",
    miroir_formule: "Misma herida + estrategia opuesta + parte repudiada portada",
    miroir_noms: {
      invisible: "La Existencia Gratuita", humilie: "La Dignidad Inatacable", abandonne: "La Presencia que Permanece",
      terrifie: "La Seguridad Encarnada", coupable: "La Inocencia Concedida", parentifie: "La Vulnerabilidad Asumida"
    },
    miroir_paires: "Los pares que te conciernen",
    miroir_triangle_titre: "El triángulo que juegan a dos",
    miroir_triangle_tes: "Tus partes juegan",
    miroir_triangle_ses: "sus partes juegan",
    miroir_triangle_theorie: "Conversión virtuosa: capítulo 10-13 →",
    miroir_stades: "Las 4 etapas del despertar",
    miroir_garde: "¿Espejo verdadero o señuelo?",
    miroir_4q: "Las 5 preguntas del espejo",
    miroir_4q_sub: "Responde libremente — las 4 primeras provienen del texto fundador « Detonante de despertar ». La 5.ª es la pregunta mágica del IFS: convierte la proyección en puerta de entrada hacia el Exiliado.",
    miroir_decodage_titre: "El descifrado de las proyecciones",
    miroir_decodage_sous: "La herencia de Carl Jung traducida al IFS: cada reacción visceral es una puerta hacia la Sombra.",
    miroir_decodage_col_reaction: "Si reacciono así…",
    miroir_decodage_col_type: "Es una proyección de…",
    miroir_decodage_col_ombre: "Lo que está encerrado en la Sombra (a reintegrar)",
    miroir_decodage_col_cle: "La pista",
    miroir_pdt_titre: "LA PIEDRA DE TOQUE — espejo",
    compat_porte_sous: "Dos perfiles cara a cara, el espejo entre ellos",
    compat_sub: "El espejo aplicado a dos sistemas: lo que cada uno desencadena en el otro.",
    compat_taux_titre: "Grado de eco espejo",
    compat_taux_sous: "Dos leyes, un solo mecanismo: misma herida (resonancia) + estrategia opuesta (complementariedad) + parte repudiada vivida sin vergüenza.",
    compat_taux_resonance: "Resonancia — misma herida",
    compat_taux_complementarite: "Complementariedad — estrategia opuesta",
    compat_taux_desavouee: "Parte repudiada — vivida sin vergüenza",
    compat_taux_seuil_faible: "Eco débil: los dos sistemas apenas se cruzan.",
    compat_taux_seuil_marque: "Eco marcado: vuestras sombras se responden — es terreno de trabajo.",
    compat_taux_seuil_intense: "Eco intenso: vuestras sombras se buscan. Este espejo es una palanca poderosa.",
    compat_peu_profils: "Necesitas al menos dos perfiles para comparar. Crea un segundo perfil desde la página de inicio.",
    compat_pas_de_donnees: "— cuestionario no completado",
    compat_managers: "Managers dominantes",
    compat_pompiers: "Bomberos de emergencia",
    compat_choisir_a: "Perfil A",
    compat_choisir_b: "Perfil B",
    compat_blessure_titre: "La herida",
    compat_blessure_oui: "Exiliados comunes en el centro — lleváis la misma herida: {noms} ({croyance})",
    compat_blessure_oui_risque: "Os entendéis sin palabras. Riesgo: nadie ve al elefante, el sistema se refuerza.",
    compat_blessure_non: "Heridas diferentes: {a} / {b}",
    compat_blessure_non_texte: "No habláis el mismo idioma de la herida. El espejo se activa por contraste: lo que le falta a uno, lo lleva el otro.",
    compat_aucune_blessure: "Ningún exiliado detectado (cuestionario vacío).",
    compat_aussi: "también: ",
    compat_danses_titre: "Danzas espejo cruzadas",
    compat_mindmap_titre: "Mapa mental de ambos sistemas",
    compat_danses_sub: "Las parejas del espejo donde se encuentran vuestros dos sistemas.",
    compat_attraction: "{a} hace {profil_a} (vía {viaA}) — {b} lleva el espejo: {miroir_b} (vía {viaB})",
    compat_meme_role: "Mismo papel en la misma danza — {a} vía {viaA}, {b} vía {viaB}: {profil_a}",
    compat_aucune_danse: "Ninguna pareja del espejo cruza estos dos sistemas.",
    compat_langages_titre: "Cómo el otro espera disculpas",
    compat_langages_sous: "Según sus partes dominantes:",
    compat_langages_vide: "Completa el cuestionario de este perfil para saberlo.",
    compat_attachement_titre: "La danza de apego",
    compat_attachement_evitant: "Evitativo ↔ Preocupado",
    compat_attachement_fuyards: "Dos huidizos: cada uno se retira, nadie persigue. La falta se instala en silencio.",
    compat_attachement_poursuivants: "Dos perseguidores: intensidad sin retirada. La ansiedad sube rápido, la demanda desborda.",
    compat_attachement_chaos: "Desorganizado en juego — acercarse-huir:",
    compat_attachement_aucun: "Ningún estilo de apego dominante detectado.",
    compat_projections_titre: "Proyecciones cruzadas",
    compat_projections_sous: "Lo que cada uno proyecta sobre el otro — la regla de oro: lo que me irrita o me fascina en el otro es una parte de mí que aún no conozco.",
    compat_proj_vers: "{a} proyecta sobre {b}",
    compat_proj_ombre_managers: "Sombra oscura — el Manager juzga en el otro lo que exilió:",
    compat_proj_ombre_pompiers: "Sombra oscura — en crisis, el Bombero verá una amenaza:",
    compat_proj_or: "Sombra dorada — el oro que el Exiliado delega:",
    theorie_recherche: "Buscar en la teoría…",
    theorie_titre: "Teoría — el Sistema Triaxial",
    theorie_lus: "leídos",
    quand_label: "Cuándo:",
    engagements_titre: "Compromisos — la carta a ti mismo",
    engagements_sub: "Cada compromiso convierte un patrón identificado en un gesto observable. Puedes reformular, quitar, añadir — es TU carta.",
    rapport_titre_prefix: "CONDUCTA INVERSA — ",
    wipe_confirm: "¿Borrar todo? Esta acción es definitiva. Puedes exportar tu sesión primero.",
    wipe_done: "Todo borrado. Esta página no guardó nada.",
    partielle: "Lectura parcial — completa tu cuestionario cuando quieras.",
    clique_carte: "Exiliado en el centro — Managers que protegen — Bomberos que extinguen. Haz clic en un círculo para ver su ficha.",
    clique_cycle: "Haz clic en una estación del ciclo para leerla.",
    cycle_selecteur: "Ver el ciclo desde:",
    signature_selecteur: "Ver el detalle de:",
    carte_selecteur: "Ver el mapa de:",
    carte_globale_titre: "Tu constelación de partes",
    carte_globale_legende: "Vista general — los 3 exiliados dominantes en el centro, los managers que protegen y los bomberos que extinguen alrededor. Haz clic en un círculo para ver su ficha.",
    carte_vue_label: "Mostrar:",
    carte_vue_globale: "Constelación — vista general",
    signature_vue_label: "Ver:",
    signature_vue_recit: "Relato",
    signature_vue_fiche: "Ficha detallada",
    pdt_selecteur: "Piedra de toque de:",
    chemin_selecteur: "Paso de la secuencia:",
    constellation_plein_ecran: "Pantalla completa",
    constellation_fermer: "Cerrar",
    clique_chemin: "Haz clic en un hito para ver qué se juega allí.",
    /* tarjeta personalizada (3 exiliados) + modo crisis + ponderación modo simple */
    pdt_carte_titre: "Mi piedra de toque",
    pdt_carte_sous: "Una palabra personalizada, construida sobre tus {n} exiliados principales — {noms}.",
    crise_btn: "No estoy bien",
    crise_titre: "No estoy bien",
    crise_sub: "No analizamos nada: apagamos. Tu sistema está en alerta — no es momento de entender, es momento de asegurar.",
    crise_consigne: "No decidas nada importante hoy. Un sistema en alerta no toma buenas decisiones.",
    crise_respi_titre: "La respiración 4-7-8",
    crise_respi_etapes: "Inhala por la nariz 4 segundos — Retén 7 segundos — Exhala por la boca 8 segundos",
    crise_respi_conseil: "Repite 4 ciclos. Si puedes, pon una mano en el vientre y otra en el corazón.",
    crise_urgence_titre: "Si es una emergencia",
    crise_liens_titre: "Cuando el cuerpo se calma",
    crise_liens_texte: "Dos protocolos de la teoría, para hacer una vez recuperado el aliento:",
    miroir_micro_titre: "El despertar en micro-pasos — márcalos cuando los hagas",
    miroir_micro_compat: "Micro-pasos del despertar",
    miroir_boucles: "Los bucles de interacción",
    miroir_boucle_cycle: "El ping-pong",
    miroir_boucle_sortie: "Cómo romper el bucle",
    conflit_titre: "Lo que este comportamiento desencadena en los demás",
    conflit_danse: "La danza previsible:",
    conflit_lien: "Ver el par en el Espejo →",
    arret_label: "En el momento",
    hub_arret_titre: "Tengo ganas de…",
    hub_arret_sub: "Elige una conducta — aparece el protocolo de parada inmediata.",
    hub_langages_titre: "Mis lenguajes del amor principales",
    hub_langages_sous: "Según tus partes dominantes — cómo nutrirlas.",
    hub_langages_vide: "Completa el cuestionario para descubrir tus lenguajes.",
    hub_proactif_titre: "Mi guardia proactiva",
    hub_proactif_sous: "El detonante se corta la víspera, no en el momento. Marca lo que hiciste hoy.",
    hub_proactif_du_jour: "Práctica del día",
    hub_proactif_quotidien: "diario",
    hub_proactif_hebdo: "semanal",
    hub_proactif_coreg: "Una conversación real con una persona segura, esta semana",
    hub_proactif_vide: "Completa el cuestionario para construir tu guardia.",
    hub_ikigai_titre: "Tu ofrenda — el Ikigai",
    hub_ikigai_sous: "Lo que tu Exiliado buscó toda su vida es lo que mejor puedes ofrecer.",
    hub_ikigai_quand: "Módulo de la fase 6 (Acción comprometida): explóralo una vez conocido el Exiliado — tu Exiliado central es {exil}. Antes, sería una estrategia más.",
    hub_ikigai_archetypes: "Tus arquetipos de genio",
    hub_ikigai_activites: "Actividades-espejo — probar la ofrenda sin revolucionarlo todo",
    hub_ikigai_piege: "La falsa pista a vigilar:",
    hub_ikigai_theorie: "Leer el capítulo « El Ikigai: aquello por lo que te levantas » →",
    tendance_homme: "♂ más reportado en hombres",
    tendance_femme: "♀ más reportado en mujeres",
    tendance_note: "Tendencias reportadas — nunca una regla individual.",
    ponderation_titre: "Una ponderación para el conjunto",
    ponderation_sub: "Estas conductas las vivo más bien… La frecuencia y la antigüedad afinan el peso de todos tus reconocimientos.",
    /* el detonante — la prueba de verdad */
    declencheur_titre: "El detonante — la prueba de verdad",
    declencheur_sous: "La palabra inversa de la piedra de toque: ataca deliberadamente tu herida, para comprobar si la hipótesis es la correcta. Si te toca, el cuerpo reconoce a su exiliado. Si te deja frío, es información, no un veredicto.",
    declencheur_consigne: "Hazlo en frío, nunca en crisis, nunca bajo los efectos de una sustancia. Puedes parar en cualquier momento.",
    declencheur_consentir: "Lo entiendo — mostrar la palabra",
    declencheur_masquer: "Ocultar la palabra",
    declencheur_choisir: "Palabra de:",
    declencheur_observation_titre: "Lo que escuchas",
    declencheur_observation: ["El cuerpo: garganta apretada, pecho, vientre, lágrimas", "La emoción: vergüenza, vacío, miedo, culpa", "La intensidad: de 0 (nada) a 10 (insoportable)", "La parte que responde: ¿quién habla en ti?"],
    declencheur_question: "¿Ha resonado?",
    declencheur_reponses: { fort: "Sí, fuerte", peu: "Un poco", non: "Nada" },
    declencheur_interpretation: {
      fort: "Resonancia fuerte — la hipótesis es probable: la herida está ahí, y la palabra la tocó. Vuelve a tu piedra de toque para dejarla.",
      peu: "Resonancia ligera — la hipótesis sigue abierta. Puedes probar otro exiliado, o volver más tarde.",
      non: "Sin resonancia — probablemente no es el exiliado correcto. No es un fracaso: es información. Prueba otro exiliado."
    },
    declencheur_antidote: "Volver a mi piedra de toque",
    declencheur_respi: "La respiración 4-7-8",
    declencheur_synthese_titre: "Tu síntesis",
    declencheur_synthese_points: "Puntos acumulados: {points}/{max}",
    declencheur_synthese_rapport: "Tu informe clasificó: {liste}.",
    declencheur_synthese_confirme: "La palabra confirma tu informe: {nom} está en el centro.",
    declencheur_synthese_ecart: "La palabra señala a {nom}, mientras que tu informe puso a {rapport} en primer lugar — la hipótesis debe reajustarse.",
    declencheur_synthese_aucune: "Sin confirmación por ahora: las palabras no resonaron. El informe sigue siendo una hipótesis a verificar.",
    declencheur_synthese_vide: "Responde a la autoevaluación de al menos una palabra: tu síntesis aparecerá aquí.",
    affinage_titre: "Precisión — 3 preguntas para afinar tu lectura",
    affinage_sub: "Tres preguntas rápidas, antes de tu informe. Afinan el descifrado: quién manda de verdad, y qué exiliado está en el centro. Si no lo sabes, pasa — no inventamos.",
    affinage_question_prefix: "Pregunta",
    affinage_passer: "Saltar esta pregunta",
    affinage_note: "3 preguntas rápidas pueden afinar tu lectura: quién manda, y qué exiliado está en el centro.",
    affinage_cta: "Precisar mi lectura →",
    affinage_refaire: "Afinar mis respuestas",
    profils_titre: "Tus perfiles",
    analyse_nom: "Análisis de comportamiento",
    analyse_sub: "Decodifica una combinación precisa — p. ej. Alcohol · A « Soy un inútil, bebo para apagar la voz que me lo repite ». Descubre la coalición de partes que la produce: el exiliado que empuja, el manager que protege, el bombero que apaga — y el camino inverso.",
    analyse_recherche: "Escribe: alcohol, scroll, ira, huida…",
    analyse_porte_sous: "Decodifica una conducta precisa: las partes que la juegan, qué protege, el camino ideal.",
    analyse_coalition: "La coalición — las tres partes en juego",
    analyse_moteur: "El motor", analyse_strategie: "La estrategia", analyse_crise: "La crisis",
    profils_sous: "Cada perfil guarda sus respuestas, su informe y su carta. Elige uno o crea uno nuevo.",
    profil_nouveau: "Nuevo perfil",
    profil_continuer: "Continuar",
    profil_supprimer: "Eliminar",
    profil_confirm_suppression: "¿Eliminar este perfil? Se perderán sus respuestas, informe y carta.",
    profil_aucun: "Aún no hay ningún perfil.",
    profil_changer: "Cambiar de perfil",
    ans: "años",
    accueil_titre_nouveau: "Nuevo perfil",
    accueil_qui: "¿Cómo te llamas?",
    accueil_placeholder: "Tu nombre",
    accueil_tu_es: "Eres…",
    accueil_age: "Tu edad:",
    accueil_alerte: "Completa tu nombre, perfil y edad para empezar.",
    langue_label: "Idioma",
    /* etiquetas compartidas (análisis, informe, ficha, espejo) */
    famille_label: "FAMILIA",
    phase_label: "Fase",
    combinaison_label: "Combinación",
    phrase_interieure_label: "Frase interior",
    declencheur_label: "Detonante",
    protege_label: "Lo que protege",
    cout_label: "Costo",
    besoin_vise_label: "Necesidad vital desviada",
    ideal_label: "Comportamiento ideal",
    miroir_comportement_label: "Comportamiento espejo",
    micro_pas_label: "Micro-pasos",
    micro_pas_semaine_label: "Micro-pasos semana 1",
    analyse_combo_entete: "Comportamiento {id} — {nom} · combinación {lettre}",
    analyse_inconnue: "Combinación desconocida.",
    analyse_tout_deplier: "Desplegar todo", analyse_tout_replier: "Plegar todo",
    seq_phases: "<b>Ser</b> (Polivagal — asegurar) → <b>Sentir</b> (IFS — conocer las partes) → <b>Actuar</b> (ACT — micro-pasos hacia los valores)",
    scores_exiles: "Exiliados", scores_managers: "Managers", scores_pompiers: "Bomberos",
    fiche_blessure: "Herida", fiche_croyance: "Creencia", fiche_part_desavouee: "Parte repudiada",
    fiche_strategie: "Estrategia", fiche_peur: "Miedo", fiche_crise: "Crisis", fiche_alternative: "Alternativa",
    fiche_nouveau_role: "Nuevo rol", fiche_lieu_corporel: "Lugar corporal",
    fiche_origine: "El origen (0-7 años)", fiche_vocabulaire: "Las palabras que vuelven", fiche_morphologie: "El cuerpo que habla",
    fiche_signatures: "Firmas", fiche_protecteurs: "Protectores", fiche_pompiers: "Bomberos extintores",
    chemin_blocage: "Lo que puede bloquear:",
    miroir_meme_blessure: "— misma herida que tú: «{croyance}». Vive sin filtro lo que tuviste que encerrar:",
    miroir_origine_titre: "El origen: la clave parental",
    miroir_origine_theorie: "Leer «Las 5 heridas y las 5 máscaras» (capítulo 4-5) →",
    miroir_triangle_vie_titre: "El triángulo de la vida",
    miroir_triangle_exemple: "El ejemplo",
    bilan_soir_titre: "El balance de la noche",
    bilan_soir_sub: "El ritual de fin de día: qué parte tomó el mando, cómo te sentiste — y el derecho a perdonarte.",
    bilan_soir_part_label: "La parte que tomó el mando hoy",
    bilan_soir_senti_label: "Cómo me sentí",
    bilan_soir_pardonner: "Me perdono — me doy el derecho de haber usado esta parte",
    bilan_soir_vide: "Elige una parte, luego una palabra para tu emoción, luego perdónate.",
    bilan_soir_fait: "Balance de la noche: {part} — {senti}. Perdónate, y mañana es otro día.",
    bilan_soir_reset: "Empezar de nuevo mañana",
    affinage_sentis_titre: "¿No encuentras tu emoción? Otras palabras para decirla:",
    declencheur_sentis_titre: "Palabras para la emoción",
    miroir_dynamique: "Dinámica de apego predicha:",
    miroir_blessure_commune: "Herida común:",
    miroir_active: "Lo que B activa en ti:",
    miroir_reveil: "El despertar:",
    miroir_piege: "La trampa:",
    miroir_en_crise: "En crisis:",
    miroir_aucune_paire: "Ninguno de los 28 pares canónicos corresponde directamente a tu perfil: tu espejo es más singular. El cálculo anterior sigue siendo válido.",
    miroir_indice: "Pista", miroir_vrai: "Espejo verdadero", miroir_leurre: "Señuelo",
    miroir_stade: "Etapa", miroir_piege_court: "Trampa:",
    miroir_reponse: "Tu respuesta…",
    import_reussi: "Importación exitosa.",
    import_impossible: "Importación imposible: ",
    /* términos de micro-pasos → capítulo de teoría (hipervínculos) */
    liens_theorie: { "4-7-8": "livre-3/3-2", "orientación": "livre-2/2-1", "anclaje": "livre-3/3-3", "reparentalización": "livre-4/4-4", "respiración": "livre-3/3-2" }
  };

  var DICTS = { fr: STR_FR, en: STR_EN, es: STR_ES };
  var STR = STR_FR;
  var genre_accord = { homme: 0, femme: 1, autre: 1 };

  function setLang(l) {
    STR = DICTS[l] || STR_FR;
  }

  /* Résolution de {clef:champ} et {accord:m:f[:e]} avec le contexte du résultat */
  function resolv(token, ctx) {
    if (token === "date") return fmtDate(new Date());
    if (token === "patterns_resume") return ctx.patterns_resume || "";
    if (token === "exiles_tous") return ctx.exiles_tous || "";
    if (token === "declencheurs_top") return ctx.declencheurs_top || "";
    if (token === "couts_top") return ctx.couts_top || "";
    if (token.indexOf(":") === -1) return ctx[token] !== undefined ? ctx[token] : "";
    var parts = token.split(":");
    var key = parts[0], field = parts[1];
    if (key === "profil") return ctx.profil ? (ctx.profil[field] || "") : "";
    var part = ctx.parts && ctx.parts[key] ? ctx.parts[key] : null;
    if (!part) return "";
    return part[field] !== undefined && part[field] !== null ? part[field] : "";
  }

  function tpl(str, ctx) {
    if (!str) return "";
    return str
      .replace(/\{accord:([^}:]+):([^}:]+)(?::([^}]+))?\}/g, function (m, f, g, e) {
        var idx = ctx.profil && ctx.profil.genre === "homme" ? 0 : 1;
        return idx === 0 ? f : (idx === 1 ? g : (e !== undefined ? e : g));
      })
      .replace(/\{([a-z0-9_]+(?::[a-z0-9_éèàâêîôûçùïüœ]+)?)\}/gi, function (m, tok) {
        var v = resolv(tok, ctx);
        return v !== undefined && v !== null ? String(v) : m;
      });
  }

  function fmtDate(d) {
    return d.toISOString().slice(0, 10).split("-").reverse().join("/");
  }
  function isoDate(d) {
    return d.toISOString().slice(0, 10);
  }

  var api = { setLang: setLang, tpl: tpl, fmtDate: fmtDate, isoDate: isoDate, genre_accord: genre_accord };
  /* STR vivant : les modules lisent HA.strings.STR à l'usage, jamais capturé au chargement */
  Object.defineProperty(api, "STR", { get: function () { return STR; } });
  return api;
})();
